name: Update cloudflare adblocking lists

on:
  schedule:
  - cron: '0 2 * * fri'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Masks
      shell: bash
      run: echo "Secrets ::add-mask::${{ secrets.API_TOKEN }} - ::add-mask::${{ secrets.IDENTIFIER }} - ::add-mask::${{ secrets.SLACK_URL }}"

    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements.txt

    - name: Execute update script
      run: python src/main.py ${{ secrets.API_TOKEN }} ${{ secrets.IDENTIFIER }} ${{ secrets.SLACK_URL }}
